- name: install nginx
  ansible.builtin.yum:
    name: nginx
    state: installed

- name: remove dir
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: absent

- name: create dir
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: directory

- name: download extract
  ansible.builtin.unarchive:
    src: https://roboshop-artifacts.s3.amazonaws.com/frontend.zip
    dest: /usr/share/nginx/html
    remote_src: yes

- name: copy paste conf
  ansible.builtin.copy:
    src: roboshop.conf
    dest: /etc/nginx/default.d/roboshop.conf

- name: start nginx
  ansible.builtin.systemd:
    name: nginx
    state: restarted
    enabled: yes
    daemon_reload: yes



