- name: install nginx
  ansible.builtin.yum:
    name: nginx
    state: installed

- name: remove dir
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: absent

- name: create dir
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: directory

#- name: download extract
#  ansible.builtin.unarchive:
#    src: https://roboshop-artifacts.s3.amazonaws.com/frontend.zip
#    dest: /usr/share/nginx/html
#    remote_src: yes

- name: download extract
  ansible.builtin.unarchive:
    src: http://{{ lookup('amazon.aws.aws_ssm', '{{env}}.nexus.user', region='us-east-1') }}:{{ lookup('amazon.aws.aws_ssm', '{{env}}.nexus.pass', region='us-east-1') }}@172.31.30.104:8081/repository/{{component}}/{{component}}-{{app_version}}.zip
    dest: /usr/share/nginx/html
    remote_src: yes

- name: update nginx conf
  template:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf

- name: copy conf file
  template:
    src: roboshop.conf
    dest: /etc/nginx/default.d/roboshop.conf

- name: start nginx
  ansible.builtin.systemd:
    name: nginx
    state: restarted
    enabled: yes
    daemon_reload: yes



