- name: install repo
  ansible.builtin.shell: https://packagecloud.io/install/repositories/rabbitmq/erlang/script.rpm.sh

- name: install rabbitmq
  ansible.builtin.dnf:
    name:
    - rabbitmq-server
    - erlang
    state: installed

- name: start rabbitmq
  ansible.builtin.systemd:
    name: rabbitmq-server
    state: restarted
    enabled: yes

- name: set pass rabbitmq
  community.rabbitmq.rabbitmq_user:
    user: roboshop
    password: roboshop123
    vhost: /
    configure_priv: .*
    read_priv: .*
    write_priv: .*
    state: present