- name: copy repo
  template:
    src: elastic.repo
    dest: /etc/yum.repos.d/

- name: install fb
  yum:
    name: filebeat
    state: installed

- name: enable and start
  systemd:
    name: filebeat
    state: restarted
    enabled: yes
    daemon-reload: yes