- name: download node
  unarchive:
    src: "{{ exporter_url }}"
    dest: /opt
    remote_src: true

- name: service node
  template:
    src: exporter.service
    dest: /etc/systemd/system/node_exporter.service

- name: start node
  systemd:
    name: node_exporter
    enabled: yes
    state: restarted
    daemon-reload: yes