- name: install prometheus server
  import_tasks:
    file: prom.yml
  when: prometheus_server

- name: install node exporter
  import_tasks:
    file: exporter.yml
  when: node_exporter

- name: install grafana
  import_tasks:
    file: grafana.yml
  when: grafana

- name: install grafana
  import_tasks:
    file: alertm.yml
  when: alertm