- name: set hostname
  shell:
    set-hostname PROM

- name: install node exporter
  import_tasks:
    file: exporter.yml
  when: node_exporter

- name: install prometheus server
  import_tasks:
    file: prom.yml
  when: prom

- name: install grafana
  import_tasks:
    file: grafana.yml
  when: prom

- name: install grafana
  import_tasks:
    file: alertm.yml
  when: prom