- name: download prometheus
  unarchive:
    src: "{{ prom_url }}"
    dest: /opt
    remote_src: true

- name: prom server configuration
  template:
    src: prometheus.yml
    dest: /opt/{{prom_dir}}/prometheus.yml

- name: alerts p
  template:
    src: "{{item}}"
    dest: /opt/{{prom_dir}}/{{item}}
  loop: "{{alert_files}}"

- name: service p
  template:
    src: prometheus.service
    dest: /etc/systemd/system/prometheus.service

- name: start p
  systemd:
    name: prometheus
    state: restarted
    enabled: yes
    daemon_reload: yes