- name: download prometheus
  unarchive:
    src: "{{ prom_url }}"
    dest: /opt
    remote_src: true

- name: prom config
  template:
    src: prometheus.yml
    dest: /opt/{{prom_dir}}/prometheus.yml

- name: prom service
  template:
    src: prometheus.service
    dest: /etc/systemd/system/prometheus.service

- name: restart
  systemd:
    name: prometheus
    state: restarted
    enabled: yes
    daemon_reload: yes

- name: copy repo
  copy:
    src: grafana.repo
    dest: /etc/yum.repos.d/grafana.repo
    remote_src: true

- name: install grafana
  yum:
    name: grafana
    state: installed

- name: enable and start
  systemd:
    name: grafana
    enabled: yes
    state: restarted