- name: add user
  ansible.builtin.user:
    name: roboshop

- name: remove dir
  ansible.builtin.file:
    path: /app
    state: absent

- name: create dir
  ansible.builtin.file:
    path: /app
    state: directory

## downloading from s3 ##
#- name: download extract
#  ansible.builtin.unarchive:
#    src: https://roboshop-artifacts.s3.amazonaws.com/{{component}}.zip
#    dest: /app
#    remote_src: yes

## downloading from the nexus ##
- name: download extract
  ansible.builtin.unarchive:
    src: http://admin:admin@172.31.30.104:8081/repository/{{component}}/{{component}}-{{app_version}}.zip
    dest: /app
    remote_src: yes