- name: set hostname
  shell:
    set-hostname {{component}}

- name: import role exporter
  import_role:
    name: prometheus
    tasks_from: exporter
  when: node_exporter

- name: filebeat
  import_role:
    name: elk
    tasks_from: filebeat
  when: filebeat