- name: dis nodejs
  ansible.builtin.shell:
    dnf module disable nodejs -y

- name: dis nodejs
  ansible.builtin.shell:
    dnf module enable nodejs:18 -y

- name: dis nodejs
  ansible.builtin.dnf:
    name: nodejs
    state: installed

- name: import task pre
  ansible.builtin.import_tasks:
    file: app-prereq.yml

- name: npm dep
  community.general.npm:
    path: /app

- name: import task sche
  ansible.builtin.import_tasks:
    file: schema-setup.yml
    when: "{{ schema_type }} is defined"

- name: import task syd
  ansible.builtin.import_tasks:
    file: systemd-setup.yml