- name: dis nodejs
  ansible.builtin.shell:
    dnf module disable nodejs -y

- name: dis nodejs
  ansible.builtin.shell:
    dnf module enable nodejs:18 -y

- name: dis nodejs
  ansible.builtin.dnf:
    name: nodejs
    state: installed

- name: import task pre
  ansible.builtin.import_task:
    file: app-prereq.yml

- name: npm dep
  community.general.npm:
    path: /app

- name: import task pre
  ansible.builtin.import_task:
    file: schema-setup
    when: schema_type.yml

- name: import task pre
  ansible.builtin.import_task:
    file: systemd-setup.yml