- name: install python
  yum:
    name: python36, gcc, python3-devel
    state: installed

- name: pre req
  import_tasks:
    file: app-prereq.yml

- name: depen
  pip:
    requirements: /app/requirements.txt
    executable: pip3.6

- name: schema
  import_tasks:
    file: schema-setup.yml
  when: schema_type is defined

- name: sysd
  import_tasks:
    file: systemd-setup.yml