- name: copy install when mongo
  when: schema_type == "mongo"
  block:
    - name: copy mongo
      ansible.builtin.copy:
        src: mongo.repo
        dest: /etc/yum.repos.d

    - name: install mongo
      ansible.builtin.dnf:
        name: mongodb-org-shell
        state: installed

    - name: download mongodb pem file
      get_url:
        url: https://s3.amazonaws.com/rds-downloads/rds-combined-ca-bundle.pem
        dest: /app/rds-combined-ca-bundle.pem

    - name: load schema mongo
#      ansible.builtin.shell:
#        mongo --host dev-mongodb.devtb.online </app/schema/{{component}}.js
      ansible.builtin.shell:
        mongo --ssl --host {{ lookup('amazon.aws.aws_ssm', '{{env}}.docdb.endpoint', region='us-east-1') }}:27017 --sslCAFile /app/rds-combined-ca-bundle.pem --username {{ lookup('amazon.aws.aws_ssm', '{{env}}.docdb.user', region='us-east-1') }} --password {{ lookup('amazon.aws.aws_ssm', '{{env}}.docdb.pass', region='us-east-1') }} </app/schema/{{component}}.js

- name: install mysql when
  when: schema_type == "mysql"
  block:
    - name: install mysql
      ansible.builtin.yum:
        name: mysql
        state: installed

    - name: load schema mysql
      ansible.builtin.shell:
        mysql --host {{ lookup('amazon.aws.aws_ssm', '{{env}}.rds.endpoint', region='us-east-1') }} -u{{ lookup('amazon.aws.aws_ssm', '{{env}}.rds.user', region='us-east-1') }} -p{{ lookup('amazon.aws.aws_ssm', '{{env}}.rds.pass', region='us-east-1') }} < /app/schema/{{component}}.sql
      ignore_errors: yes