- name: copy install when mongo
  when: schema_type == "mongo"
  block:
    - name: copy mongo
      ansible.builtin.copy:
        src: mongo.repo
        dest: /etc/yum.repos.d

    - name: install mongo
      ansible.builtin.dnf:
        name: mongodb-org-shell
        state: installed

    - name: load schema
      ansible.builtin.shell:
        mongo --host mongodb.devtb.online </app/schema/catalogue.js

- name: install mysql when
  when: schema_type == "mysql"
  block:
    - name: install
      ansible.builtin.yum:
        name: mysql
        state: installed

    - name: load schema
      ansible.builtin.shell:
        mysql --host mysql.devtb.online -uroot -pRoboShop@1 </app/schema/shipping.sql