- name: copy ser file
  ansible.builtin.copy:
    src: {{ component }}.service
    dest: /etc/systemd/system

- name: start ser
  ansible.builtin.systemd:
    name: "{{ component }}"
    state: restarted
    enabled: yes
    daemon-reload: yes