- name: copy ser file
  ansible.builtin.template:
    src: "{{component}}.service"
    dest: /etc/systemd/system/{{component}}.service

- name: start ser
  ansible.builtin.systemd:
    name: "{{component}}"
    state: restarted
    enabled: yes
    daemon-reload: yes