prometheus_server: false
node_exporter: false
exporter_url: https://github.com/prometheus/node_exporter/releases/download/v1.7.0/node_exporter-1.7.0.linux-amd64.tar.gz
exporter_dir: "{{ exporter_url | split('/') | last | regexp_replace ('.tar.gz', '') }}"

prom_url: https://github.com/prometheus/prometheus/releases/download/v2.50.0-rc.0/prometheus-2.50.0-rc.0.linux-amd64.tar.gz
prom_dir: "{{ prom_url | split('/') | last | regexp_replace ('.tar.gz', '') }}"