#route:
#  group_by: ['alertname']
#  group_wait: 30s
#  group_interval: 5m
#  repeat_interval: 1h
#  receiver: 'web.hook'
#receivers:
#  - name: "email"
#    email_configs:
#      - to: skiliyas300@gmail.com
#        from: skiliyas300@gmail.com
#        smarthost: "email-smtp.us-east-1.amazonaws.com:587"
#        auth_username: "{{SES_SMTP_USERNAME}}"
#        auth_password: "{{SES_SMTP_PASSWORD}}"
#        require_tls: tr
#inhibit_rules:
#  - source_match:
#      severity: 'critical'
#    target_match:
#      severity: 'warning'
#    equal: ['alertname', 'dev', 'instance']
route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
  receiver: 'web.hook'
receivers:
  - name: 'web.hook'
    webhook_configs:
      - url: 'http://127.0.0.1:5001/'
inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']
