global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets:

rule_files:
{% for file in alert_files %}
  - {{ file }}
{% endfor %}

scrape_configs:
  - job_name: "roboshop-nodes"

    ec2_sd_configs:
      - region: us-east-1
        port: 9100
        filters:
          - name: "tag:Monitor"
            values: ["yes"]

    relabel_configs:
      - source_labels: [__meta_ec2_tag_Name]
        target_label: "name"