groups:
  - name: roboshop
    rules:
    {% for component in components %}

      - alert: Service Down - {{component.name}} service
        expr: node_systemd_unit_state{exported_name="{{component.service}}.service",state="active"} < 1
        for: 30s
        labels:
          severity: critical
          appName: {{component.name}}
        annotations:
          summary: Service down on this server {{component.name}} - {{component.service}}.service
    {% endfor %}