groups:
  - name: roboshop
    rules:
      - alert: ServiceDown
        expr: node_systemd_unit_state{exported_name="nginx.service",state="active"} < 1
        for: 30s
        labels:
          severity: critical
          appName: cart
        annotations:
          summary: Service down on some server - service name - cart.service